version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: golang-app
    hostname: golang-app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    image: webmakaka/golang-app

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

networks:
  default:
    driver: bridge
    name: golang-app-network
